import { boolean, integer, pgTable, text, timestamp } from "drizzle-orm/pg-core"

export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }) })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").defaultNow(), updatedAt: timestamp("updatedAt").defaultNow() })

export const products = pgTable("products", { id: text("id").primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), brand: text("brand").notNull(), category: text("category").notNull(), gender: text("gender").notNull(), size: text("size").notNull(), condition: text("condition").notNull(), conditionNotes: text("condition_notes").notNull(), price: integer("price").notNull(), compareAtPrice: integer("compare_at_price"), imageUrl: text("image_url").notNull(), imageAlt: text("image_alt").notNull(), color: text("color").notNull(), isFeatured: boolean("is_featured").notNull().default(false), isActive: boolean("is_active").notNull().default(true), stock: integer("stock").notNull().default(1), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() })
export const addresses = pgTable("addresses", { id: text("id").primaryKey(), userId: text("user_id").notNull(), label: text("label").notNull(), fullName: text("full_name").notNull(), phone: text("phone").notNull(), city: text("city").notNull(), addressLine: text("address_line").notNull(), postalCode: text("postal_code"), isDefault: boolean("is_default").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() })
export const orders = pgTable("orders", { id: text("id").primaryKey(), orderNumber: text("order_number").notNull().unique(), userId: text("user_id"), customerName: text("customer_name").notNull(), email: text("email").notNull(), phone: text("phone").notNull(), city: text("city").notNull(), addressLine: text("address_line").notNull(), postalCode: text("postal_code"), paymentMethod: text("payment_method").notNull(), paymentStatus: text("payment_status").notNull().default("pending"), status: text("status").notNull().default("placed"), subtotal: integer("subtotal").notNull(), shippingFee: integer("shipping_fee").notNull(), total: integer("total").notNull(), notes: text("notes"), trackingNumber: text("tracking_number"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() })
export const orderItems = pgTable("order_items", { id: text("id").primaryKey(), orderId: text("order_id").notNull(), productId: text("product_id").notNull(), productName: text("product_name").notNull(), size: text("size").notNull(), quantity: integer("quantity").notNull(), unitPrice: integer("unit_price").notNull(), imageUrl: text("image_url").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() })
