import Image from "next/image"
import Link from "next/link"
import { ArrowRight, BadgeCheck, BrushCleaning, PackageCheck, Truck } from "lucide-react"
import type { Product } from "@/lib/store-data"
import { ProductCard } from "@/components/product-card"

export function HomePage({ products }: { products: Product[] }) {
  return <>
    <section className="mx-auto grid max-w-7xl gap-6 px-4 py-6 md:grid-cols-[0.9fr_1.1fr] md:px-6 md:py-10"><div className="flex flex-col justify-center bg-secondary p-7 md:p-12"><p className="text-xs font-bold uppercase tracking-[0.25em] text-primary">Thrifted in Pakistan · Drop 04</p><h1 className="mt-5 text-balance font-serif text-5xl font-black leading-[0.95] tracking-tight md:text-7xl">Good shoes deserve another story.</h1><p className="mt-6 max-w-lg text-pretty text-base leading-7 text-muted-foreground">One-of-one pre-owned sneakers, professionally cleaned and honestly graded. Find your next favorite pair without paying retail.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="flex h-12 items-center gap-3 bg-primary px-6 font-bold text-primary-foreground">Shop the latest drop <ArrowRight size={18}/></Link><Link href="/about" className="flex h-12 items-center border border-foreground px-6 font-bold">How we grade</Link></div></div><div className="relative min-h-80 overflow-hidden bg-secondary md:min-h-[580px]"><Image src="/images/hero-shoes.png" alt="A curated pair of vintage green running shoes" fill priority className="object-cover"/><div className="absolute bottom-5 left-5 bg-background px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">This week&apos;s pick</p><p className="font-serif text-lg font-bold">Verdant Runner · EU 42</p></div></div></section>
    <section className="border-y border-border"><div className="mx-auto grid max-w-7xl grid-cols-2 md:grid-cols-4">{[[BadgeCheck,"Honest grading"],[BrushCleaning,"Deep cleaned"],[PackageCheck,"One pair only"],[Truck,"Pakistan wide"]].map(([Icon,label],i)=><div key={label as string} className={`flex items-center gap-3 border-border px-4 py-5 text-sm font-bold ${i < 3 ? "md:border-r" : ""}`}><Icon size={20} className="text-primary"/>{label as string}</div>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 md:px-6 md:py-24"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Freshly added</p><h2 className="mt-2 text-balance font-serif text-4xl font-black md:text-5xl">The latest rotation</h2></div><Link href="/shop" className="hidden items-center gap-2 text-sm font-bold md:flex">View all <ArrowRight size={16}/></Link></div><div className="grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-4 md:gap-6">{products.slice(0,4).map((product)=><ProductCard key={product.id} product={product}/>)}</div></section>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 md:grid-cols-2 md:px-6 md:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em]">The ReLace standard</p><h2 className="mt-4 text-balance font-serif text-5xl font-black leading-none">No mystery pairs. Every mark disclosed.</h2></div><div className="grid gap-7 sm:grid-cols-2"><div><span className="font-serif text-4xl font-black">01</span><h3 className="mt-3 font-bold">Inspect</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/75">We check soles, stitching, lining, shape and authenticity before listing.</p></div><div><span className="font-serif text-4xl font-black">02</span><h3 className="mt-3 font-bold">Restore</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/75">Every pair is deep-cleaned, deodorized and photographed as it is.</p></div></div></div></section>
  </>
}
