import Link from "next/link"
import { requireAdminPage } from "@/lib/auth-helpers"
import { createProduct } from "@/app/actions/products"
import { ProductMediaPicker } from "@/components/product-media-picker"
import { TYPES, GENDERS, CONDITIONS } from "@/lib/product-options"

export default async function NewProductPage() {
  await requireAdminPage()
  return <main className="min-h-svh bg-secondary"><header className="border-b border-border bg-foreground text-background"><div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-4 md:px-6"><Link href="/admin" className="font-serif text-2xl font-black">ReLace.</Link><div className="text-xs font-bold uppercase tracking-widest">Add product</div></div></header><section className="mx-auto max-w-3xl px-4 py-10 md:px-6"><h1 className="font-serif text-4xl font-black">List a new pair.</h1><form action={createProduct} className="mt-8 flex flex-col gap-4 bg-background p-6"><div className="grid gap-4 md:grid-cols-2"><input name="name" placeholder="Name" required className="h-12 border border-input bg-card px-3"/><input name="brand" placeholder="Brand" required className="h-12 border border-input bg-card px-3"/><select name="category" required defaultValue="" className="h-12 border border-input bg-card px-3"><option value="" disabled>Type</option>{TYPES.map((type) => <option key={type} value={type}>{type}</option>)}</select><select name="gender" required defaultValue="" className="h-12 border border-input bg-card px-3"><option value="" disabled>Gender</option>{GENDERS.map((gender) => <option key={gender} value={gender}>{gender}</option>)}</select><input name="size" placeholder="Size (e.g. EU 42)" required className="h-12 border border-input bg-card px-3"/><input name="color" placeholder="Color" required className="h-12 border border-input bg-card px-3"/><select name="condition" required defaultValue="" className="h-12 border border-input bg-card px-3"><option value="" disabled>Condition</option>{CONDITIONS.map((condition) => <option key={condition} value={condition}>{condition}</option>)}</select><input name="price" type="number" min={1} placeholder="Price (PKR)" required className="h-12 border border-input bg-card px-3"/><input name="compareAtPrice" type="number" min={1} placeholder="Compare-at price (optional)" className="h-12 border border-input bg-card px-3"/><input name="stock" type="number" min={0} defaultValue={1} placeholder="Stock" required className="h-12 border border-input bg-card px-3"/></div><textarea name="conditionNotes" placeholder="Condition notes" required className="min-h-24 border border-input bg-card px-3 py-2"/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="isFeatured"/> Feature on homepage</label><ProductMediaPicker submitLabel="Create product"/></form></section></main>
}
